module github.com/appsome/ix/examples/reference

go 1.25.0

require (
	github.com/go-chi/chi/v5 v5.3.0
	github.com/lib/pq v1.12.3
	github.com/appsome/ix/runtime v0.1.0
)

require (
	github.com/Blank-Xu/sql-adapter v1.1.2 // indirect
	github.com/IguteChung/casbin-psql-watcher v1.0.0 // indirect
	github.com/beorn7/perks v1.0.1 // indirect
	github.com/bmatcuk/doublestar/v4 v4.9.1 // indirect
	github.com/casbin/casbin/v2 v2.135.0 // indirect
	github.com/casbin/govaluate v1.10.0 // indirect
	github.com/cespare/xxhash/v2 v2.3.0 // indirect
	github.com/golang-jwt/jwt/v5 v5.3.1 // indirect
	github.com/google/uuid v1.6.0 // indirect
	github.com/jackc/pgpassfile v1.0.0 // indirect
	github.com/jackc/pgservicefile v0.0.0-20200714003250-2b9c44734f2b // indirect
	github.com/jackc/pgx/v5 v5.1.1 // indirect
	github.com/jackc/puddle/v2 v2.1.2 // indirect
	github.com/munnerz/goautoneg v0.0.0-20191010083416-a7dc8b61c822 // indirect
	github.com/prometheus/client_golang v1.23.2 // indirect
	github.com/prometheus/client_model v0.6.2 // indirect
	github.com/prometheus/common v0.66.1 // indirect
	github.com/prometheus/procfs v0.16.1 // indirect
	go.uber.org/atomic v1.10.0 // indirect
	go.yaml.in/yaml/v2 v2.4.2 // indirect
	golang.org/x/crypto v0.52.0 // indirect
	golang.org/x/sync v0.20.0 // indirect
	golang.org/x/sys v0.45.0 // indirect
	golang.org/x/text v0.37.0 // indirect
	google.golang.org/protobuf v1.36.8 // indirect
)

// Until runtime/v0.1.0 is published, build against the in-repo copy. A real
// project generated by ix drops this and relies on the tagged module via
// `go get github.com/appsome/ix/runtime`.
replace github.com/appsome/ix/runtime => ../../runtime
