// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	CreateWidget(ctx context.Context, name string) (Widget, error)
	DeleteWidget(ctx context.Context, id int64) error
	GetWidget(ctx context.Context, id int64) (Widget, error)
	ListWidgets(ctx context.Context, arg ListWidgetsParams) ([]Widget, error)
}

var _ Querier = (*Queries)(nil)
